// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveInformationAPI.Data;

#nullable disable

namespace SaveInformationAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250124014459_Models-Redefinitions")]
    partial class ModelsRedefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaveInformationAPI.Models.Cancha", b =>
                {
                    b.Property<int>("IdCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCancha"));

                    b.Property<TimeSpan?>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<int>("IdComplejo")
                        .HasColumnType("int");

                    b.Property<string>("ImagenCancha")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreCancha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroJugadores")
                        .HasColumnType("int");

                    b.Property<float?>("PrecioPorHora")
                        .HasColumnType("real");

                    b.Property<int?>("complejoIdComplejo")
                        .HasColumnType("int");

                    b.HasKey("IdCancha");

                    b.HasIndex("complejoIdComplejo");

                    b.ToTable("Cancha");
                });

            modelBuilder.Entity("SaveInformationAPI.Models.Complejo", b =>
                {
                    b.Property<int>("IdComplejo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComplejo"));

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("int");

                    b.Property<string>("ImagenComplejo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreComplejo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdComplejo");

                    b.ToTable("Complejo");
                });

            modelBuilder.Entity("SaveInformationAPI.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("canchaIdCancha")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("canchaIdCancha");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("SaveInformationAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.PrimitiveCollection<string>("ComplejosAdministrados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordUsuario")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("tipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SaveInformationAPI.Models.Cancha", b =>
                {
                    b.HasOne("SaveInformationAPI.Models.Complejo", "complejo")
                        .WithMany("Canchas")
                        .HasForeignKey("complejoIdComplejo");

                    b.Navigation("complejo");
                });

            modelBuilder.Entity("SaveInformationAPI.Models.Reserva", b =>
                {
                    b.HasOne("SaveInformationAPI.Models.Cancha", "cancha")
                        .WithMany()
                        .HasForeignKey("canchaIdCancha");

                    b.Navigation("cancha");
                });

            modelBuilder.Entity("SaveInformationAPI.Models.Complejo", b =>
                {
                    b.Navigation("Canchas");
                });
#pragma warning restore 612, 618
        }
    }
}
